version: "2.3"
services:
  app:
    image: style_transfer/webapp:0.1
    build: .
    volumes:
      - /mnt/nas/tf_experiments/style_transfer_tf2/piccasso_2/export/saved_model:/opt/model
    devices:
      - /dev/video0
    ports:
      - "8080:8080"
    runtime: nvidia
