version: "2.3"
services:
  app:
    image: style_transfer/webapp:0.1
    build: .
    volumes:
      - ./models:/opt/models
    devices:
      - /dev/video0
    ports:
      - "8080:8080"
    runtime: nvidia
